version: '3'

services:
  mysql:
    hostname: mysql
    image: mysql:5.6
    ports:
      - 3306:3306
    volumes:
      - /mnt/rbd0:/var/lib/mysql
    command: --character-set-server=utf8
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-PW1
      MYSQL_DATABASE: sbtest
      MYSQL_USER: sbtest
      MYSQL_PASSWORD: my-secret-pw
  
  bench:
    image: fibird/sysbench:mysqlv2
    depends_on:
      - "mysql"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: sbtest
      MYSQL_USER: sbtest
      MYSQL_PASSWORD: my-secret-pw
  
